# Generated by Django 2.1.2 on 2018-10-24 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('complaints', models.TextField(blank=True, null=True)),
                ('bills', models.TextField(blank=True, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('point_of_contact', models.ForeignKey(blank=True, db_column='point_of_contact', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
    ]
